//! Procedurally synthesized audio (no external asset files).
//!
//! All SFX and the BGM loop are generated at startup as 16-bit PCM WAV bytes and
//! registered as in-memory `AudioSource` assets. Requires the `bevy/wav` feature
//! (default Bevy only ships the OGG/Vorbis decoder).
//!
//! Source of the audio: generated by this code (simple additive synthesis).
//! - click:  short square blip      - stir:  two low sine "plops"
//! - success: C-E-G arpeggio        - error: low square buzz
//! - burn:   two-tone square alarm  - coin:  rising sine ping
//! - bgm:    soft 8s pentatonic sine loop with a low bass pulse

use super::actions::{InputSet, UiAction};
use bevy::audio::{AudioPlayer, AudioSource, PlaybackMode, PlaybackSettings, Volume};
use bevy::prelude::*;

/// One-shot sound effects requested by gameplay systems.
#[derive(Message, Clone, Copy)]
pub enum SfxRequest {
    Click,
    Stir,
    Success,
    Error,
    Burn,
    Coin,
}

#[derive(Resource)]
pub struct Sfx {
    pub click: Handle<AudioSource>,
    pub stir: Handle<AudioSource>,
    pub success: Handle<AudioSource>,
    pub error: Handle<AudioSource>,
    pub burn: Handle<AudioSource>,
    pub coin: Handle<AudioSource>,
}

pub struct GameAudioPlugin;

impl Plugin for GameAudioPlugin {
    fn build(&self, app: &mut App) {
        app.add_message::<SfxRequest>();
        app.add_systems(Startup, setup_sfx);
        app.add_systems(
            Update,
            (play_sfx, click_on_action.after(InputSet)),
        );
    }
}

// ---- WAV encoding ----------------------------------------------------------

const SR: u32 = 22050;

fn wav_mono(samples: &[i16], sample_rate: u32) -> Vec<u8> {
    let data_len = (samples.len() * 2) as u32;
    let mut out = Vec::with_capacity(44 + data_len as usize);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36 + data_len).to_le_bytes());
    out.extend_from_slice(b"WAVE");
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes()); // PCM
    out.extend_from_slice(&1u16.to_le_bytes()); // mono
    out.extend_from_slice(&sample_rate.to_le_bytes());
    out.extend_from_slice(&(sample_rate * 2).to_le_bytes()); // byte rate
    out.extend_from_slice(&2u16.to_le_bytes()); // block align
    out.extend_from_slice(&16u16.to_le_bytes()); // bits per sample
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_len.to_le_bytes());
    for s in samples {
        out.extend_from_slice(&s.to_le_bytes());
    }
    out
}

#[derive(Clone, Copy)]
enum Wave {
    Sine,
    Square,
}

/// Additive synthesis: `tones` = (freq, start_secs, duration, amplitude).
fn synth(dur: f32, tones: &[(f32, f32, f32, f32)], wave: Wave) -> Vec<i16> {
    let sr = SR as f32;
    let n = (dur * sr) as usize;
    let mut buf = vec![0.0f32; n];
    for &(freq, start, td, amp) in tones {
        let s0 = (start * sr) as usize;
        let s1 = ((start + td) * sr).min(n as f32) as usize;
        for i in s0..s1 {
            let t = (i - s0) as f32 / sr;
            let v = match wave {
                Wave::Sine => (std::f32::consts::TAU * freq * t).sin(),
                Wave::Square => {
                    if (freq * t).fract() < 0.5 {
                        1.0
                    } else {
                        -1.0
                    }
                }
            };
            let attack = (t / 0.008).min(1.0);
            let release = ((td - t) / (0.02 + td * 0.22)).clamp(0.0, 1.0);
            let env = attack.min(release).min(1.0);
            buf[i] += v * amp * env;
        }
    }
    let peak = buf.iter().fold(0.0f32, |m, x| m.max(x.abs())).max(0.001);
    let scale = (0.85 / peak).min(1.0);
    buf.iter()
        .map(|x| {
            let v = (x * scale * i16::MAX as f32).round();
            v.clamp(i16::MIN as f32, i16::MAX as f32) as i16
        })
        .collect()
}

fn setup_sfx(mut commands: Commands, mut assets: ResMut<Assets<AudioSource>>) {
    let mut register = |samples: Vec<i16>| -> Handle<AudioSource> {
        assets.add(AudioSource {
            bytes: wav_mono(&samples, SR).into(),
        })
    };

    let click = register(synth(0.06, &[(880.0, 0.0, 0.05, 0.6)], Wave::Square));
    let stir = register(synth(
        0.20,
        &[
            (150.0, 0.0, 0.09, 0.5),
            (210.0, 0.09, 0.09, 0.42),
            (170.0, 0.0, 0.18, 0.12), // low rumble
        ],
        Wave::Sine,
    ));
    let success = register(synth(
        0.60,
        &[
            (523.25, 0.0, 0.18, 0.5),
            (659.25, 0.16, 0.18, 0.5),
            (783.99, 0.32, 0.26, 0.55),
        ],
        Wave::Sine,
    ));
    let error = register(synth(0.22, &[(130.0, 0.0, 0.20, 0.5)], Wave::Square));
    let burn = register(synth(
        0.55,
        &[
            (660.0, 0.0, 0.12, 0.4),
            (440.0, 0.12, 0.12, 0.4),
            (660.0, 0.24, 0.12, 0.4),
            (440.0, 0.36, 0.12, 0.4),
        ],
        Wave::Square,
    ));
    let coin = register(synth(
        0.18,
        &[(1180.0, 0.0, 0.07, 0.4), (1580.0, 0.06, 0.11, 0.42)],
        Wave::Sine,
    ));

    commands.insert_resource(Sfx {
        click,
        stir,
        success,
        error,
        burn,
        coin,
    });

    // BGM: gentle 8s pentatonic loop.
    let melody = [261.63, 293.66, 329.63, 392.0, 440.0, 392.0, 329.63, 293.66];
    let mut tones: Vec<(f32, f32, f32, f32)> = Vec::new();
    for rep in 0..4 {
        for (i, &f) in melody.iter().enumerate() {
            let t0 = (rep * melody.len() + i) as f32 * 0.5;
            tones.push((f, t0, 0.40, 0.13));
        }
    }
    for i in 0..8 {
        tones.push((130.81, i as f32 * 1.0, 0.85, 0.09));
    }
    let bgm = register(synth(8.0, &tones, Wave::Sine));
    commands.spawn((
        AudioPlayer(bgm),
        PlaybackSettings {
            mode: PlaybackMode::Loop,
            volume: Volume::Linear(0.16),
            ..default()
        },
    ));
}

/// Play requested one-shots.
fn play_sfx(
    mut requests: MessageReader<SfxRequest>,
    sfx: Res<Sfx>,
    mut commands: Commands,
) {
    for r in requests.read() {
        let handle = match r {
            SfxRequest::Click => &sfx.click,
            SfxRequest::Stir => &sfx.stir,
            SfxRequest::Success => &sfx.success,
            SfxRequest::Error => &sfx.error,
            SfxRequest::Burn => &sfx.burn,
            SfxRequest::Coin => &sfx.coin,
        };
        commands.spawn((
            AudioPlayer(handle.clone()),
            PlaybackSettings {
                mode: PlaybackMode::Despawn,
                volume: Volume::Linear(0.5),
                ..default()
            },
        ));
    }
}

/// Every user action gets a soft click as immediate tactile feedback.
fn click_on_action(
    mut actions: MessageReader<UiAction>,
    mut sfx: MessageWriter<SfxRequest>,
) {
    if actions.read().next().is_some() {
        sfx.write(SfxRequest::Click);
    }
}
